### ISSUE TITLE
Permission denied for competiton forum

### ISSUE THREAD

**Issue by anandhperumal** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#1]
I was trying to access the competition forum, but I got error 418 "Permission denied"
Let me know if I'm missing anything

**Comment by wangcunxiang** [comment]
Hi Anandh,

I'm sorry. We mistakenly wrote a wrong link in the github. The correct one should be 'https://competitions.codalab.org/competitions/21080'. 
And we corrected it in the github project just noe.

Thanks a lot for your interest in the project and your email.

Best Wishes


wangcunxiang1997@gmail.com
 
From: Anandh Perumal
Date: 2019-10-04 14:40
To: wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation
CC: Subscribed
Subject: [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation] Permission denied for competiton forum (#1)
I was trying to access the competition forum, but I got error 418 "Permission denied"
Let me know if I'm missing anything
