### ISSUE TITLE
Answers about test data of Subtask A/B

### ISSUE THREAD

**Issue by im0qianqian** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#1]
Hello, when do you plan to release the test data answers for Subtask A/B?
Or, if the Post-Evaluation phase is over, how should I continue to test the performance of my model?

Thanks!

**Comment by wangcunxiang** [comment]
Hi, qianqian. We decide not to release the gold label for the test set for now, and you can use dev set for error analysis. You can also submit to Post Evaluation phase to evaluate your system on test set.

**Comment by im0qianqian** [comment]
In other words, when the Post-Evaluation phase is over, I will not be able to use test data for testing, is it?

**Comment by wangcunxiang** [comment]
We will not end the Post-Evaluation phase. If you find that you cannot submit the results to it, please let us know as soon as possible, we will fix it.

**Comment by im0qianqian** [comment]
okay, thank you~
