### ISSUE TITLE
Subtask A Trial Data Labels

### ISSUE THREAD

**Issue by AliOsm** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#2]
I think that subtask A trial data labels are flipped. For example, the first instance in the trial data is:
sent0: he put an elephant into the fridge
sent1: he put a turkey into the fridge
And the label for it is: 0, which tell us that the commonsense sentence is "he put an elephant into the fridge".
This can be noted in all instances.

**Comment by SamuelCahyawijaya** [comment]
@AliOsm : Based on https://competitions.codalab.org/competitions/21080#learn_the_details-overview, task A objective is to find which sentence **against** the common sense. So the labels should be correct.

<img width="837" alt="Screen Shot 2019-10-07 at 15 57 54" src="https://user-images.githubusercontent.com/2826602/66294289-3428f900-e91b-11e9-9f75-f9add44faaf9.png">

**Comment by AliOsm** [comment]
@SamuelCahyawijaya so the flipped labels are in the training data not in the trial, because the sentences in the second example in the training data are:
sent0: He drinks apple.
sent1: He drinks milk.
And the label is 1, so the sentence against the common sense is "He drinks milk.",  which is not correct. And the same thing repeats in the other examples. The point that I want to clarify is that the labels of the training and trial datasets are not in the same convention.

**Comment by wangcunxiang** [comment]
Thanks so much your carefulness. 
We have flipped the answers of subtaskA of the training data(0->1, 1->0) and updated subtaskA_answers_all.csv.

**Comment by AliOsm** [comment]
Thanks for the update.
