### ISSUE TITLE
Similar examples in Subtask A training data

### ISSUE THREAD

**Issue by AliOsm** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#3]
There are 5 similar pairs in the training data of Subtask A:

4075 | You may see a cat flying in the sky | You may see a cat flying in the sky
4121 | my mother prond of me | my mother prond of me
4314 | When we are frightened, we are happy | When we are frightened, we are afraid
6398 | The desk lamp illuminates the room | The desk lamp illuminates the room
7700 | He went to college at the age of two | He went to college at the age of two

Such cases didn't appear in the trial data.

**Comment by Shuailong** [comment]
> There are 5 similar pairs in the training data of Subtask A:
> 
> 4075 | You may see a cat flying in the sky | You may see a cat flying in the sky
> 4121 | my mother prond of me | my mother prond of me
> 4314 | When we are frightened, we are happy | When we are frightened, we are afraid
> 6398 | The desk lamp illuminates the room | The desk lamp illuminates the room
> 7700 | He went to college at the age of two | He went to college at the age of two
> 
> Such cases didn't appear in the trial data.
@AliOsm We have done some screening to ensure the data quality, but unfortunately we missed these cases, thanks for pointing out! Actually you may or may not use these cases as part of your training data to train the model. Your model will be eligible anyway to participate in the competition. (you are welcome to use additional resources, too)
