### ISSUE TITLE
open-source projects that were trained to test cs validation task?

### ISSUE THREAD

**Issue by AnaRhisT94** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#3]
Hi,
Where can I see open-source projects that were trained to give good results on cs validation task?

Thanks a lot!

**Comment by wangcunxiang** [comment]
https://github.com/huggingface/transformers/tree/master/examples/legacy/multiple_choice can give nice results.
In addition, you can check in Semeval-2020 task 4 task participation papers to see whether they have released their codes.

**Comment by AnaRhisT94** [comment]
> https://github.com/huggingface/transformers/tree/master/examples/legacy/multiple_choice can give nice results. In addition, you can check in Semeval-2020 task 4 task participation papers to see whether they have released their codes.


Are there any common sense datasets for validation that have 100k+ sentences?

**Comment by wangcunxiang** [comment]
Sorry, I do not know whether there are other "common sense datasets for validation ".
