### ISSUE TITLE
email is bouncing 

### ISSUE THREAD

**Issue by anandhperumal** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#6]
This email address semeval-2020-task-4-organizers@googlegroups.com <semeval-2020-task-4-organizers@googlegroups.com> is bouncing.
Is there any other email address to contact the organizers.
I'm posting this here since I'm not able to join the competition forum.

**Comment by HunterHeidy** [comment]
me too ，Haven't received it yet

**Comment by anandhperumal** [comment]
@HunterHeidy I spoke to the organizers, it seems if we don't mail them from Gmail then the emails bounces. That is fixed now so closing the issue.
