### ISSUE TITLE
subtaskB_data_all.csv misses some (3?) sentences 

### ISSUE THREAD

**Issue by piteren** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#7]
subtaskB_data_all.csv got only 4 fields in examples #5618 #7238 #9941 (only 2 options, but should be 3).
Do I have to assume that OptionC = '' ?

**Comment by wangcunxiang** [comment]
Hi,

Thanks for your carefulness. 

I'm sorry that It's our mistake to leave 3 missing OptionCs.

You can treat them as ''.

**Comment by piteren** [comment]
Hi, sure, no problem.
